services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - VITE_APP_API_URL=http://localhost:3006
      - WATCHPACK_POLLING=true
    depends_on:
      - api
    networks:
      - app-network

  api:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./db.json:/app/db.json
    ports:
      - "3006:3006"
    command: >
      sh -c "npm install -g json-server && json-server --watch db.json --host 0.0.0.0 --port 3006"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge